name: 'JS App CI/CD Template'

on:
  workflow_call:
    secrets:
      ACR_PASSWORD:
        required: true
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    name: 'Application Build'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
            
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ vars.ACR_NAME }}.azurecr.io/javaapp:${{ github.sha }} .
          docker push ${{ vars.ACR_NAME }}.azurecr.io/javaapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [build]
  
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Update Azure Container App with new image
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: "${{ vars.ACR_NAME }}.azurecr.io/javaapp:${{ github.sha }}"
          containerAppName: javaapplication
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
